name: 自动部署

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
      
    - name: 腾讯云依赖
      run: |
        npm install -g @cloudbase/cli

    - name: 腾讯云登录
      run: |
        tcb login --apiKeyId ${{ secrets.APIKEYID }}  --apiKey ${{ secrets.APIKEY }}

    - name: 腾讯云部署
      run: |
        mkdir push
        cp -a *[^push] push
        tcb hosting deploy push -e images-8glumyyd4754ac02